### ISSUE TITLE
No current progress area or scrollbar, I also can't scroll using my mousewheel or pageup/pagedown

### ISSUE THREAD

**Issue by aidanjmaunder** [flathub/tech.feliciano.pocket-casts#5]
I can't see the progress area that's usually at the bottom of the app when playing an episode.

I'm also unable to scroll anywhere in the app. The mousewheel does nothing, and the scrollbar is hidden. I can see it for a second when the app boots, but it vanishes after a second.

![Screenshot from 2023-10-17 14-19-27](https://github.com/flathub/tech.feliciano.pocket-casts/assets/12162800/1b68d4dc-2934-48c8-b38f-767d9a69e30f)

I'm using: `Pop!_OS 22.04 LTS x86_64`

**Comment by nclm** [comment]
I have the same issue, opened https://github.com/felicianotech/pocket-casts-desktop-app/issues/91 a minute ago as I didn’t see yours here.

**Comment by hadess** [comment]
Seeing as the package didn't change, I'm going to assume that this is something for the app to adapt to. I'll close this in favour of the upstream issue, thanks for filing it.
