### ISSUE TITLE
Link from Flathub

### ISSUE THREAD

**Issue by nclm** [flathub/tech.feliciano.pocket-casts#6]
The links for that app should point to https://github.com/felicianotech/pocket-casts-desktop-app/ (the actual app) and not to https://pocketcasts.com (the service this app displays).

**Comment by hadess** [comment]
It's what the original author links to:
https://github.com/felicianotech/pocket-casts-desktop-app/blob/trunk/flatpak/tech.feliciano.pocket-casts.appdata.xml

Feel free to file an issue at https://github.com/felicianotech/pocket-casts-desktop-app/issues to see if the upstream author agrees to change it.
